on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  type-check:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Generate
        run: yarn generate
      - name: Typecheck
        run: yarn tsc --noEmit
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lint
  summary:
    name: Summary
    runs-on: ubuntu-latest
    needs: [type-check, lint]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install Dependancies
        run: yarn install --frozen-lockfile
      - name: Generate
        run: yarn generate
      - name: Build
        run: yarn build --metafile
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist
