on:
  workflow_call:
  pull_request:
    branches:
      - main

name: Lint

jobs:
  typecheck:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - name: Install Dependancies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
