on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Type Check

jobs:
  typecheck:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        name: Install PNPM
        with:
          version: 8
      - name: Setup Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependancies
        run: pnpm install --frozen-lockfile
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/tsc.json"
      - name: Check Types
        run: pnpm tsc --noEmit
