on:
  workflow_call:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Type Check

jobs:
  typecheck:
    name: Check Types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'node'
      - name: Install Dependancies
        run: pnpm install --frozen-lockfile
      - name: Generate
        run: pnpm generate
      - name: Add Problem Matcher
        run: echo "::add-matcher::.github/problem-matchers/tsc.json"
      - name: Check Types
        run: pnpm tsc --noEmit
